# database
spring:
    datasource:
        url: jdbc:log4jdbc:mysql://localhost:3306/shopping-mall?serverTimezone=UTC&characterEncoding=UTF-8
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: root
        password: Root1234!@#$
    mvc:
        view:
            suffix: .html
    devtools:
        restart:
            log-condition-evaluation-delta: false
    thymeleaf:
        check-template-location: true
        cache: false # 개발 시에는 false로 두는게 좋음

# mybatis
mybatis:
    type-aliases-package: com.nicky.shoppingmall.config, com.nicky.shoppingmall.domain, java.util
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: mybatis/mapper/*.xml

flyway:
    baseline-on-migrate: true
    locations: db/migration
    baseline-version: 1
# logging
logging:
    config: classpath:logback-default.xml

jwt:
    secret: asdl;kfasl;dkf;a'lskdf;laksdflajsdlkfjasdfsdfaksldfjlksdjflkasdjfklsdf
